all: build
CXX    = c++
CPPFLAGS += -fno-rtti -fno-exceptions -shared -D_POSIX_ -O3
TEST_DEFINES = -D_POSIX_
GECKO_SDK_PATH = ../gecko-sdk
GECKO_DEFINES   = -DXPCOM_GLUE -DMOZILLA_STRICT_API
GECKO_IDL_INCLUDES = -I $(GECKO_SDK_PATH)/idl
GECKO_INCLUDES = -I  $(GECKO_SDK_PATH)/include
GECKO_LDFLAGS =   -L $(GECKO_SDK_PATH)/lib -lxpcomglue -lnspr4 -lplds4 -lembed_base_s

nsIMoulin.h: nsIMoulin.idl
	$(GECKO_SDK_PATH)/bin/xpidl -m header $(GECKO_IDL_INCLUDES) nsIMoulin.idl

moulin.xpt: nsIMoulin.idl
	$(GECKO_SDK_PATH)/bin/xpidl -m typelib $(GECKO_IDL_INCLUDES) -o moulin nsIMoulin.idl
	
moulin.so: nsMoulin.cpp
	$(CXX) -o moulin.so -DXPCOM_BUILD $(GECKO_DEFINES) $(GECKO_INCLUDES) $(GECKO_LDFLAGS) $(CPPFLAGS) $(CXXFLAGS) nsMoulin.cpp /usr/lib/libbz2.a /usr/lib/libz.a
	chmod +x moulin.so

build: moulin.so moulin.xpt
	
clean:
	rm moulin.so moulin.xpt

